
name: Zip and Upload Resource Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Delete the existing tag if it exists
      - name: Delete Existing Tag
        run: |
          git tag -d latest || true
          git push origin --delete latest || true
      # Recreate the tag
      - name: Recreate Tag
        run: |
          git tag latest
          git push origin latest
      # Zip the repository contents
      - name: Create ZIP Archive
        run: |
          zip -r RP.zip .
      # Create or update the release
      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: latest
          name: Latest Release
          artifacts: RP.zip
          replacesArtifacts: true
